### ISSUE TITLE
getting this issue

### ISSUE THREAD

**Issue by ishu9565** [notsapinho/instagram-profile-downloader#1]
npm notice
npm notice New minor version of npm available! 7.11.2 -> 7.13.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.13.0
npm notice Run npm install -g npm@7.13.0 to update!
npm notice

up to date, audited 1 package in 1s

found 0 vulnerabilities
npm notice
npm notice New minor version of npm available! 7.11.2 -> 7.13.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.13.0
npm notice Run npm install -g npm@7.13.0 to update!
npm notice

C:\Users\Ishu Gupta>npm start
npm ERR! Missing script: "start"
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ishu Gupta\AppData\Local\npm-cache\_logs\2021-05-15T11_12_18_440Z-debug.log

**Comment by notsapinho** [comment]
i believe you are not running `npm start` on the app folder
